travis:
  secure:
    BINSTAR_TOKEN: P4CroszFCCmiUNKWaiAhtqvt5ZhO1Q1uCOkDHpXpoj21LPFQpQ7TqhQVgWrfPIM0xEcv9LDiTYISeYPb2PRW2EgzViWftOtTDF1sg/ei3VNf/1to8HLRUUX4bvCnRH+/ema6rvaBBkhBDQDaHk2KSGh1XfFUOtT8V9konEvnPePNo8v6I3W2vDha1A5UGZEbhSae/7Ibzr6FKGTGVkJRg0vSrsZNppshMTrRwnR+s5wnWMnKcHNptMwZLOh5JLRoLlkIX41YFZTdeBQ1zdxaIw+LICiFlyMvYrhMhHCF9gvMnfH64AE354soITPHEO0yDDDcPd+IcTQSzA3D50jQmA272Z8BGtenxJTKhnjthAVa+MCg+o8qXYWu0a469aylB4ujVHxi/Euap8kjVi8dsCASRLjarf+905BVqZgC+IRMHboxVTVOKzkuH+VtOY5C1TuiDly30gK9yolBtIk0hh0Rqms12u3+SE4dPQN+HplFmn7uDbt8sX5Vjsl0J6S400XXoOXywfGeRBoV/bBpjWaX1i4ThpZ2qGTWuZR7UFezUI3Pe2gRJB0iURhtWGRpad4R/OhpTiW4FYYv91yeo1y091lahvK7XhkFl/GQBu67fDLupGny8ou63Skp/OMvd4tKD0zyJYAQrc6T1zUDSieyHq8Oub0bDk9lXKAkUhY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
