travis:
  secure:
    BINSTAR_TOKEN: SvGOaAjCLrKGLGBY4le2hl88HcULis2FM6M6ofBkoreYze4KAJMEQtcN5uTXX0HQD5GohAZt8I/QNo0r1ftTdG22j07LqOf+ftutt7o3hQdTled/Owm1KRtrEez/O4ysPQuzr9FD3uwXPShOYsBKiI25mSnPrGlkW/GTKyw6Nzr9Nlbw74J9V4d/7NBdXJ3mFw5BIu/D7nZq6NPJOMGIkZVMR6Yx04yvhMU+YZnOofezYYrYrt0mrfkvM/d6QEtZCjEOJNKGp+N5L6HUOx4IlIuMp+zAy7k0ygj/OXwtTCGVQjxJnjbojGjyrfQgceaXYXfFWpwXRKW8tAFgWpAgV+yjPSlyT6kdfQEmcjqSI5cUvYJpTW/ofSyrgB4jNUVLF2WIBeVkMsqZxFU+bgU3Sa+p/KpIpKFVK/FyXKFfaBuivTeNhXn2KS6GUlVHoqiE8Jw2/VM5bv3n00/YAvhKvj7P1VpY0D0muj/TOcYiYWiclpeL4X0HPv3LCLtQolipWArOT6aI59t2Qsp41hybSTorjeOj99MYkIGX/JwvI3eVoep09z8WK8Y7rPXXum/7s9SGZDczJSCefapog7yRj2AyTDe85oL0k7U7JO/TelfVr1tPwTLypGM0oGvHc7IVxNd9FlSMS+TFNOqKv9EiXGkXyWdGRol87OncWza3pZw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
