travis:
  secure:
    BINSTAR_TOKEN: rWEKON3Hm2y3QWJ+JkfUlT4b0/9N9DS7gAdo48CiNt2AA4rX0B7rYQ70XfZ2xQK4UTJqREVHWPBHATzW5r9e36ysagJtwY5Oy5uV1qEE+aIM044mdzxSMWrTKA3HiINUEG0wyEc9e0RjXrkHXVrojymhpDSEVfXZuIFkKkDR3POGukK2KJDgfV0XZ8e3FwIXIp9iSddgmsjaAVtllsmuUXWW7eCkoFUKRSniTIrvptozAn8WoTwEzh9Ckv/VtIYHntiuoBuIuFOO/7Ak0WbWHNV83RqKBxaE3p45KRyACm7XzW5ucxoGIFxXFLufarz8cJhkAHxNgT92kVprQvsi2K+x65OVPrDoyuIBYB4dAj2mAeVB3/w3lf6tooMQPMOdatnzfM+GILL+2gn7X5R30weLtE6XXk2wuYplsuHLXbQrg+SvAC4khSJ/k7egpYNMBPtC2W9pszionRzWLWyP5GaB02l0s32Dr6/+RkPj4LkcXKgkYs7SagBfQUY5FpwUMujS7n+1NKKW+MLRGpkuTW9AziDI3rK96BkHSl0XrrhbH8Zdv1ilsFWSEr13ee3GgHiCJ/7A9jA/KbbUnneNMK206wkNyqbAnRXw0xW0y37labGymgxhPY5e/uxO85t68USGJs0/J2IUnyOIUhsPszbGXt59Lia5JcJ7jarXusA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
